language: c

compiler:
- clang
- gcc

script: make && make test && make clean

notifications:
  slack:
    secure: RHC6BxRur6okc1RgGXjcQmMUz8Dk/92x00Yhq6WxYAX5B1kJ8tApi2LhptIKrvSQnlz1LVqifJ27rhZWxuay2HHYRgYXWWtjBHIK96SDNYcBf8QKyp+xVi0UgiPN5oWJkVqE9NDJvD3YeF2QwdZX3OSkE13AWm7Zo00/XrXc8uXy8o7KQh+/GEMmlmxueHD/nZHpiSY6BYrAL+MbW5uJBlTr2t/+C2mKcokNLpYTRWyV6kzFhaTsNDp11bdzquLAidlHVy/rEn5y9mZim2BeGHoTiFP0rDptPPBAT3u3OUz6yrVZpbBcSV/bAv27j1uFSksikYGEg+ZQZeDxAljEqJCutkqu185AWVPqYdBm/OCXb/JOpWBkju+R7d8MmqxUux4nT5bvwxRHeI+HkXWuFWSRKPR75cFcg53bZQPVezSCwd5E8aYKQ4Rx1rfc3evhcfVN8zzZkEFpW3mGCShA2+nUnwnOf5HJX/hqAz7N1NFRZtR0WG4PzXCYY5bNDb8v90JFr+iDAzCAaz5soCcGMHTd0u946VIJwUlldF/odA5alhAZI+7/aoRdYzvWeYiWMAyQGHg0i/mfSJIMSOfrphoqfa36a0NayAuWpcxdt4WJSfm85M0g3j6mVUzfTpky3miNLD/xk4H8+6QJgD/pKgJLDlvCayWjhjbGY+VYs80=
